# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
jobs:
- job: testDtsCriticWithDt
  pool:
    vmImage: 'ubuntu-latest'
    demands: npm

  timeoutInMinutes: 360

  steps:
  - task: Npm@1
    displayName: 'npm install'
    inputs:
      verbose: false

  - script: 'rm -r node_modules/dts-critic && ln -s "$(pwd)" node_modules/dts-critic'
    displayName: 'ln -s "$(pwd)" node_modules/dts_critic'
  
  - script: 'node node_modules/typescript/lib/tsc.js && node node_modules/dtslint-runner/bin/index.js --clone --onlyTestTsNext'
    displayName: 'node node_modules/dtslint-runner/bin/index.js --clone --onlyTestTsNext'

trigger:
- master

# steps:
# - task: NodeTool@0
#   inputs:
#     versionSpec: '10.x'
#   displayName: 'Install Node.js'

# - script: |
#     npm install
#     npm run build
#   displayName: 'npm install and build'
